### ISSUE TITLE
systemd hangs

### ISSUE THREAD

**Issue by AkinoKaede** [EmixamPP/linux-enable-ir-emitter#101]
**Describe the bug**

After the program successfully generated driver, the configure program didn't stop.
So I just kill the program by  pressing `Control+C`, and it works even I reboot my laptop.

But when the laptop wake up from S3 Sleep State, the ir emitter cannot work correctly. I must use  `sudo linux-enable-ir-emitter run` to re run it.

**How to reproduce**

```
> sudo linux-enable-ir-emitter -v -d /dev/video2 configure                      
    
INFO: Ensure to not use the camera during the execution.
INFO: Warning to do not kill the process !
Is the ir emitter flashing (not just turn on) ? Yes/No ? No 
DEBUG: Computing the resolution control.
DEBUG: Minimum not consistent, it will be ignored.
DEBUG: current: 0 0
DEBUG: maximum: 2 100
DEBUG: resolution: 1 50
DEBUG: unit: 13 selector: 14
DEBUG: new current: 1 50
Is the ir emitter flashing (not just turn on) ? Yes/No ? Yes
INFO: The driver has been successfully generated.
```

**Additional info**
 - Computer (or camera) model: `Bus 001 Device 002: ID 13d3:5419 IMC Networks Integrated Camera`
 - Version of linux-enable-ir-emitter: `4.5.0`

Status of systemd service:

```
linux-enable-ir-emitter.service - enable the infrared emitter
     Loaded: loaded (/usr/lib/systemd/system/linux-enable-ir-emitter.service; enabled; preset: disabled)
     Active: inactive (dead)
```

**Comment by AkinoKaede** [comment]
It seems it is caused by systemd, systemd cannot start linux-enable-ir-emitter.service.

**Comment by EmixamPP** [comment]
Unfortunately, I really don't have time to look at that now, it will only be in July

**Comment by AkinoKaede** [comment]
> Unfortunately, I really don't have time to look at that now, it will only be in July

It doesn't matter, I will try my best to solve the problem by myself.

**Comment by AkinoKaede** [comment]
For workaround, I create and script:

```
# > /lib/systemd/system-sleep/linux-enable-ir-emitter

#!/bin/sh

case $1 in
    post) /usr/bin/linux-enable-ir-emitter run  ;;
esac
```

It's works for me.

**Comment by EmixamPP** [comment]
What is your distro ? 

And could you please execute: `sudo /sbin/modprobe uvcvideo`. Does the command terminate ?

**Comment by AkinoKaede** [comment]
> What is your distro ?
> 
> And could you please execute: `sudo /sbin/modprobe uvcvideo`. Does the command terminate ?

Hmm, I am using Arch Linux, the command are not terminated.
Actually, I tried to remove ExecStartPre from service, but it still terminate.

**Comment by EmixamPP** [comment]
So even without `ExecStartPre = /sbin/modprobe uvcvideo`  in `linux-enable-ir-emitter.service`, the command `sudo linux-enable-ir-emitter boot enable` command still hangs?

**Comment by AkinoKaede** [comment]
> sudo linux-enable-ir-emitter boot enable

Yes

**Comment by AkinoKaede** [comment]
> I've tried something in #115. In the PR there is a comment with a link to download the tarball that contains the (possible) fix.
> 
> Could you please test this version? Thank you

systemd hangs is fixed, but it not start after suspend.

**Comment by AkinoKaede** [comment]
> > I've tried something in #115. In the PR there is a comment with a link to download the tarball that contains the (possible) fix.
> > Could you please test this version? Thank you
> 
> systemd hangs is fixed, but it not start after suspend.

I deleted `multi-user.target` in `After`, it is fixed.

```
[Unit]
Description = enable the infrared emitter
After = suspend.target hybrid-sleep.target hibernate.target suspend-then-hibernate.target

[Service]
Type = oneshot
ExecStartPre = /sbin/modprobe uvcvideo
ExecStart = /usr/bin/linux-enable-ir-emitter run

[Install]
WantedBy = suspend.target hybrid-sleep.target hibernate.target suspend-then-hibernate.target
```

**Comment by EmixamPP** [comment]
Could you also test this one : 
```
[Unit]
Description = enable the infrared emitter
After=suspend.target sleep.target hibernate.target hybrid-sleep.target suspend-then-hibernate.target

[Service]
Type = oneshot
ExecStartPre = /sbin/modprobe uvcvideo
ExecStart = /usr/bin/linux-enable-ir-emitter run

[Install]
WantedBy=multi-user.target
```
It is more "correct"

**Comment by AkinoKaede** [comment]
> That makes sens, there were a dependency loop, I think.
> 
> Could you also test this one please :
> 
> ```
> [Unit]
> Description = enable the infrared emitter
> After=suspend.target sleep.target hibernate.target hybrid-sleep.target suspend-then-hibernate.target
> 
> [Service]
> Type = oneshot
> ExecStartPre = /sbin/modprobe uvcvideo
> ExecStart = /usr/bin/linux-enable-ir-emitter run
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> It is more "correct"

It not works.

**Comment by AkinoKaede** [comment]
I add `multi-user.target` to `WantedBy`, I think it is correct.

```
[Unit]
Description = enable the infrared emitter
After = suspend.target hybrid-sleep.target hibernate.target suspend-then-hibernate.target

[Service]
Type = oneshot
ExecStartPre = /sbin/modprobe uvcvideo
ExecStart = /usr/bin/linux-enable-ir-emitter run

[Install]
WantedBy = multi-user.target suspend.target sleep.target hibernate.target hybrid-sleep.target suspend-then-hibernate.target
```

**Comment by EmixamPP** [comment]
So it was hanging because `multi-user.target` was also in `After=`

Great! Thank you so much for your contribution to the project!

**Comment by EmixamPP** [comment]
Also, I see that you removed `sleep.target` from `After=` is this on purpose?

**Comment by AkinoKaede** [comment]
> Also, I see that you removed `sleep.target` from `After=` is this on purpose?

This does not appear to be in the `After`.

<https://github.com/EmixamPP/linux-enable-ir-emitter/blob/7eb24b4fe65328c2520ac169c41825e9a96c9273/sources/boot_service/systemd/linux-enable-ir-emitter.service>

**Comment by AkinoKaede** [comment]
I removed udev rule and reboot my laptop, it works.

**Comment by EmixamPP** [comment]
> This does not appear to be in the After.

Ok mistakes from my part. 

> I removed udev rule and reboot my laptop, it works.

Ok then, I think I can merge the fix

Thanks again :smile:

**Comment by AkinoKaede** [comment]
You are welcome.

**Comment by AkinoKaede** [comment]
I found out the reason, it was caused by the udev process being stuck, which was caused by the Linux kernel, linux-enable-ir-emitter was fine. Changes should probably be revert.
