### ISSUE TITLE
Running configure complains about no 'Session DBus', doesn't respond to key presses

### ISSUE THREAD

**Issue by ironveil** [EmixamPP/linux-enable-ir-emitter#126]
**Describe the bug**
Updated from v4.x.x to v5, and it no longer works. Initially, the camera turns on without the IR emitter.

Tried to reconfigure the IR emitter via `sudo linux-enable-ir-emitter configure`. However, it came up with this message, and it wouldn't respond to Y/N:

```
INFO: Ensure to not use the camera during the execution.
INFO: Warning to do not kill the process !
INFO: Configuring the camera: /dev/v4l/by-path/pci-0000:03:00.4-usb-0:4:1.2-video-index0.
Is the video flashing? Press Y or N
qt.qpa.theme.dbus: Session DBus not running.
qt.qpa.theme.dbus: Application will not react to setting changes.
 Check your DBus installation.
```

I am unsure what the session DBus is referring to, and I couldn't find a result on Google for it.

**How to reproduce**
1. Update from v4.x.x to v5
2. Re-run configure
3. ???

**Additional info**
 - Device: Lenovo Yoga Slim 7 1313ACN5
 - Camera: Bus 003 Device 003: ID 04f2:b6cb Chicony Electronics Co., Ltd Integrated Camera (not sure if this is the correct one)
 - Linux: Arch Linux (latest version, latest linux-zen kernel (6.4.9))
 - Version of program: 5.0.0

**Comment by EmixamPP** [comment]
Could you please test the installation instruction provided in the readme?
