### ISSUE TITLE
Configuration lost and Emitter not working at boot after powered down for a long time, requires reconfiguration each time

### ISSUE THREAD

**Issue by SWi7CHbladE** [EmixamPP/linux-enable-ir-emitter#171]
**Describe the bug**

**How to reproduce**

**Additional info**
 - Computer (or camera) model:  Lenovo yoga 7 14ARP8, AMD Ryzen 7 7735u, Bus 005 Device 002: ID 04f2:b7b4 Chicony Electronics Co., Ltd Integrated Camera
 - Linux distribution: Fedora 39
 - Version of linux-enable-ir-emitter:

**Comment by SWi7CHbladE** [comment]
Version of linux-enable-ir-emitter is 6.0.0

**Comment by EmixamPP** [comment]
Please open an issue using the right template. Otherwise, I have no information to help you.
