### ISSUE TITLE
Can't access to config file during boot

### ISSUE THREAD

**Issue by furcelay** [EmixamPP/linux-enable-ir-emitter#23]
Hi, first of all, thanks for your work,

The quick configuration work for me but it stops working after reboot. It's seems that the configuration path is wrong before login, 

```python
save_config_file_path = os.path.expanduser("~") + "/.irConfig.yaml"
```

`expanduser("~")` in `command.py` gives a wrong path in this case.

Thanks!

**Comment by EmixamPP** [comment]
For some strange reason this error does not happen to me. 

I have pushed a patch, so unfortunately all commands must be run as an administrator. 

Thank you for your help !

**Comment by furcelay** [comment]
The problem is solved, thanks! :smile:
