### ISSUE TITLE
Uncorrect command help

### ISSUE THREAD

**Issue by jeroen1243** [EmixamPP/linux-enable-ir-emitter#30]
*************
A configuration have been found. Here is what you can do:
	- activate the emitter at system startup : 'linux-ir-emitter boot enable'
	- manually activate the emitter for one session : 'linux-ir-emitter run'
*************

These commands don't work and should be:
linux-enable-ir-emitter boot enable
linux-enable-ir-emitter boot run

**Comment by EmixamPP** [comment]
Thank you! It will be fixed in my next commit.
