### ISSUE TITLE
Launch script loads too early in systemd

### ISSUE THREAD

**Issue by garabulho** [EmixamPP/linux-enable-ir-emitter#7]
I have a Dell XPS 9310 2in1. Everything works fine except service script.

I get this at startup 

"enable-ir-emitter[355]: Unable to open a file descriptor for /dev/video2"

I think launch script run before video drivers. How can we fix?

**Comment by EmixamPP** [comment]
Someone under Manjaro had the same issue as you and he managed to fix this problem by adding an udev rules.
Take a look at: https://github.com/EmixamPP/linux-enable-ir-emitter/issues/1#issuecomment-717458823.
