### ISSUE TITLE
Since v4 the emitter no longer works on Lenovo Yoga Slim 7 14ARE05

### ISSUE THREAD

**Issue by mike-echo-oscar-whiskey** [EmixamPP/linux-enable-ir-emitter#71]
Since upgrading to V4 the infrared emitter on my Lenovo Yoga Slim 7 14ARE05 no longer works.

**Additional info**
 - Distro:  arch
 - Version: 5.18.7-arch1-1
 - Version of linux-enable-ir-emitter: v4
 - How did you install linux-enable-ir-emitter: AUR

**Comment by EmixamPP** [comment]
Can you please provide more information ? What does not work ? Provides the output of `linux-enable-ir-emitter boot status`

**Comment by EmixamPP** [comment]
Personally, I did not encounter any problems during the update (but I am running Fedora).

**Comment by sarvasana** [comment]
Here is the output:

```
× linux-enable-ir-emitter.service - enable the infrared emitter
     Loaded: loaded (/usr/lib/systemd/system/linux-enable-ir-emitter.service; bad; vendor preset: disabled)
     Active: failed (Result: exit-code) since Thu 2022-06-30 16:18:15 CEST; 17h ago
   Main PID: 1996 (code=exited, status=1/FAILURE)
        CPU: 53ms

jun 30 16:18:15 zerottl systemd[1]: Starting enable the infrared emitter...
jun 30 16:18:15 zerottl linux-enable-ir-emitter[1996]: CRITICAL: No driver has been configured.
jun 30 16:18:15 zerottl systemd[1]: linux-enable-ir-emitter.service: Main process exited, code=exited, status=1/FAILURE
jun 30 16:18:15 zerottl systemd[1]: linux-enable-ir-emitter.service: Failed with result 'exit-code'.
jun 30 16:18:15 zerottl systemd[1]: Failed to start enable the infrared emitter.
```

When I try to generate a driver, the infrared emitter never lights up anymore.

**Comment by EmixamPP** [comment]
Ok the driver is missing, you have to reconfigure it : 
`sudo linux-enable-ir-emitter configure`. 

Can you, before reconfigure, past me the output of : 
- `ls /etc/linux-enable-ir-emitter.yaml`
- `ls /etc/linux-enable-ir-emitter/`

In order to find a possible bug

**Comment by EmixamPP** [comment]
1. Fo debug purpose can you past the output of the v4 version of :  `sudo linux-enable-ir-emitter -v configure` 
2. Then go back to the previous version, you can download a tarball of the git at the version 3.2.5 https://github.com/EmixamPP/linux-enable-ir-emitter/releases/tag/3.2.5
3. Then reconfigure : `sudo linux-enable-ir-emitter -v configure` and past the output

Thank you for your help !

**Comment by EmixamPP** [comment]
I think that your driver has been deleted during the upgrade because the software is firstly uninstalled and then installed. 
@supdrewin it is the expected behaviour on Arch distro ? There is a fix ? Like check if it is an upgrade or a real uninstallation in the .install file

**Comment by sarvasana** [comment]
> Ok the driver is missing, you have to reconfigure it : `sudo linux-enable-ir-emitter configure`.
> 
> EDIT : I didn't saw
> 
> > When I try to generate a driver, the infrared emitter never lights up anymore.
> 
> Can you, _before reconfigure_, past the output of :
> 
>     * `ls /etc/linux-enable-ir-emitter.yaml`
> 
>     * `ls /etc/linux-enable-ir-emitter/`
```
❯ ls /etc/linux-enable-ir-emitter.yaml
.rw-r--r-- 452 root 2021-12-20 17:41  /etc/linux-enable-ir-emitter.yaml
❯ ls /etc/linux-enable-ir-emitter/
```

**Comment by sarvasana** [comment]
Here is the V4 debug output. I will post the v3.2.5 later today:

```
❯ sudo linux-enable-ir-emitter -v configure
[sudo] password for kris: 
INFO: Ensure to not use the camera during the execution.
INFO: Warning to do not kill the process !
Did you see the ir emitter flashing (not just turn on) ? Yes/No ? n
DEBUG: unit: 13, selector: 14, cur control: 0 0, first control to test: 1 10, res control: 1 10, max control: 2 100
Did you see the ir emitter flashing (not just turn on) ? Yes/No ? n
Did you see the ir emitter flashing (not just turn on) ? Yes/No ? n
Did you see the ir emitter flashing (not just turn on) ? Yes/No ? n
DEBUG: unit: 13, selector: 16, cur control: 0, first control to test: 1, res control: 1, max control: 1
Did you see the ir emitter flashing (not just turn on) ? Yes/No ? n
DEBUG: unit: 14, selector: 2, cur control: 1 0 0 0 0 0 0 16 39 0 0 0 0 0 0, first control to test: 0 0 0 0 0 0 0 16 39 0 0 0 0 0 0, res control: 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0, max control: 7 0 0 0 0 0 0 200 20 5 0 0 0 0 0
Did you see the ir emitter flashing (not just turn on) ? Yes/No ? n
Did you see the ir emitter flashing (not just turn on) ? Yes/No ? n
DEBUG: Computing the resolution control.
DEBUG: unit: 14, selector: 6, cur control: 1 3 1 0 0 0 0 0 0, first control to test: 1 3 2 0 0 0 0 0 0, res control: 0 0 1 0 0 0 0 0 0, max control: 1 3 3 0 0 0 0 0 0
Did you see the ir emitter flashing (not just turn on) ? Yes/No ? n
Did you see the ir emitter flashing (not just turn on) ? Yes/No ? n
DEBUG: unit: 14, selector: 9, cur control: 0 0 0 0, first control to test: 1 0 0 0, res control: 1 0 0 0, max control: 1 0 0 0
Did you see the ir emitter flashing (not just turn on) ? Yes/No ? n
ERROR: The configuration has failed.
INFO: Do not hesitate to visit the GitHub ! https://github.com/EmixamPP/linux-enable-ir-emitter/wiki

```

**Comment by sarvasana** [comment]
```
❯ cat /etc/linux-enable-ir-emitter.yaml
#Caution: any manual modification of this file may corrupt the operation of the program! You must therefore be very careful.
#Please consult https://github.com/EmixamPP/linux-enable-ir-emitter/wiki/Manual-configuration before.
#If you currupt the driver file: execute 'linux-enable-ir-emitter fix driver' to reset the file.

!!python/object:driver.Driver.Driver
_control:
- 1
- 3
- 3
- 0
- 0
- 0
- 0
- 0
- 0
_device: /dev/video2
_selector: 6
_unit: 14
```

I also executed the migration script.
It did not have any output.

**Comment by EmixamPP** [comment]
Does your emitter is working now ?

**Comment by EmixamPP** [comment]
Running the migration script should have made it work, as it ensures compatibility between v3 and v4. 
Can you past the output of `sudo linux-enable-ir-emitter boot status` ? 
And execute `sudo linux-enable-ir-emitter boot enable` to retrigger the boot service.

**Comment by sarvasana** [comment]
```
❯ sudo linux-enable-ir-emitter boot status
[sudo] password for kris: 
ERROR: The boot service does not exists.
❯ sudo linux-enable-ir-emitter boot enable
INFO: The boot service have been enabled.
```
