### ISSUE TITLE
runit instead of systemd

### ISSUE THREAD

**Issue by ChausseBenjamin** [EmixamPP/linux-enable-ir-emitter#88]
I noticed every time I restart my computer, my IR emitter works just fine.
But if I close my laptop lid and open it back up, it will no longer work.

**Additional info**
 - Distro: Artix Linux 
 - Version: Using runit as a service manager
 - Version of linux-enable-ir-emitter: 4.1.5
 - How did you install linux-enable-ir-emitter: git version of the AUR

**Comment by EmixamPP** [comment]
This should be easy to implement with the new integration created to support OpenRC #104

**Comment by EmixamPP** [comment]
I'm closing this issue, since it received no interest for more than one year
