### ISSUE TITLE
Emitters blinking too slowly for Howdy to recognize face

### ISSUE THREAD

**Issue by seths22** [EmixamPP/linux-enable-ir-emitter#92]
I installed the driver in Linux Mint on a brand new (2023) Dell XPS 15, it successfully made the emitters come on but they seem to blink too slowly for Howdy to recognize my face. I tried `sudo howdy test` and it showed my face not being continuously illuminated, which apparently made Howdy unable to recognize the presence of a face at all when I tried to add a face model. Is there any way to increase the blinking rate?

**Comment by EmixamPP** [comment]
You should try to increase the dark_threshold to 80 or more

**Comment by seths22** [comment]
That worked, thank you!
